# Site settings
title: Fucking blog
email: contact@israelmateo.com
description: Just another fucking blog
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://recioraszak.github.io" # the base hostname & protocol for your site
twitter_username: lannisterogilvy
github_username:  recioraszak

# Build settings
markdown: kramdown
